[project]
name = "submerge"
version = "0.1.0"
description = "A CLI tool for DIVE development."
authors = [
    {name = "Yauhen Yakimovich",email = "yauhen.yakimovich.mail@gmail.com"}
]
license = {text = "GPL3"}
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typer (>=0.15.3,<0.16.0)",
    "toml (>=0.10.2,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{include = "submerge", from="src"}]
homepage = "https://github.com/orbital-state/submerge"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
black = "^25.1.0"

[tool.poetry.scripts]
submerge = "submerge.cli:app"

